/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: flex.skl,v 1.2 94/01/04 14:33:15 vern Exp $
 */

#define FLEX_SCANNER

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#ifndef const
#define const
#endif
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.
 */
#define YY_START ((yy_start - 1) / 2)

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file".  Now included
 * only for backward compatibility with previous versions of flex.
 */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#ifdef __cplusplus
extern "C" {
#endif
	extern int yywrap YY_PROTO(( void ));
#ifdef __cplusplus
	}
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	/* Whether we've seen an EOF on this buffer. */
	int yy_eof_status;
#define EOF_NOT_SEEN 0
	/* "Pending" happens when the EOF has been seen but there's still
	 * some text to process.  Note that when we actually see the EOF,
	 * we switch the status back to "not seen" (via yyrestart()), so
	 * that the user can continue scanning by just pointing yyin at
	 * a new input file.
	 */
#define EOF_PENDING 1
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static void yyunput YY_PROTO(( int c, char *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
static void yy_push_state YY_PROTO(( int new_state ));
static void yy_pop_state YY_PROTO(( void ));
static int yy_top_state YY_PROTO(( void ));

#ifndef yytext_ptr
static void yy_flex_strcpy YY_PROTO(( char *, const char * ));
#endif

static void *yy_flex_alloc YY_PROTO(( unsigned int ));
static void *yy_flex_realloc YY_PROTO(( void *ptr, unsigned int ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define INITIAL 0
#define ebaud 1
#define edevicename 2
#define edevicespeed 3
#define ehangupstring 4
#define esendstring 5
#define esleep 6
#define ewaitnumber 7
#define econnectstring 8
#define ebusystring 9
#define enocarrierstring 10
#define enodialtonestring 11
#define eisdndevice 12
#define eisdnport 13
typedef unsigned char YY_CHAR;
typedef int yy_state_type;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
extern char *yytext;
#define yytext_ptr yytext

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( const char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_END_OF_BUFFER 45
static const short int yy_accept[327] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   45,   43,
       40,   42,   43,   43,   43,   43,   43,   43,   43,   43,
        3,    3,    3,    2,    3,    3,    3,    3,    3,    3,
        3,   24,   23,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   21,   21,   21,   20,   21,   21,   21,   21,
       21,   21,   21,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   36,   36,   33,   33,   33,   32,   33,

       33,   33,   33,   33,   33,   33,   39,   39,   39,   38,
       39,   39,   39,   39,   39,   39,   39,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   30,   29,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   40,    0,   41,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    2,   23,    0,   22,    0,

       20,    0,    5,    0,    0,   35,    0,   32,   38,    0,
        8,    0,    0,   17,    0,    0,   14,    0,    0,   11,
        0,   29,    0,   28,    0,    0,   26,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   22,    5,
       35,    8,   17,   14,   11,   28,   26,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    1,    0,    0,
        0,    0,    0,    0,    0,   34,    0,   37,    0,    0,
        0,    0,    0,    0,    0,   31,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   25,    0,    0,    0,

        0,    0,    0,   16,    0,    0,    0,    0,   19,    0,
        0,    0,    0,    0,    4,    0,    0,    7,    0,    0,
        0,    0,   13,    0,   10,    0
    } ;

static const int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    5,    5,    5,
        5,    5,    5,    5,   10,   11,   12,   13,   14,    5,
       15,   16,   17,    5,    5,   18,    5,   19,   20,   21,
        5,   22,   23,   24,   25,   26,   27,    5,   28,    5,
        5,    9,    5,    5,    5,    5,   10,   11,   12,   13,

       14,    5,   15,   16,   17,    5,    5,   18,    5,   19,
       20,   21,    5,   22,   23,   24,   25,   26,   27,    5,
       28,    5,    5,    5,    5,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const int yy_meta[29] =
    {   0,
        1,    1,    1,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2
    } ;

static const short int yy_base[338] =
    {   0,
        0,   26,   53,    0,   81,    0,  109,    0,  137,    0,
      165,    0,  193,    0,  221,    0,  249,    0,  277,    0,
      305,    0,  333,    0,  361,    0,  389,    0,  777,  778,
        4,  778,  773,    0,  755,  764,  753,  751,    0,  761,
      778,   11,  767,  761,    7,  748,  757,  746,  744,    8,
      754,  778,   32,   15,  760,   25,  742,  751,  740,  738,
       25,  748,  778,  416,  754,  748,  409,  735,  744,  733,
      731,   26,  741,  778,  419,   42,  747,  412,  729,  738,
      727,  725,  410,  735,  778,  423,  420,  741,  420,  723,
      732,  721,  719,  417,  729,  778,  434,  735,  729,  422,

      716,  725,  714,  712,  425,  722,  778,  438,  728,  722,
      423,  709,  718,  707,  705,  432,  715,  778,  447,  435,
      721,  442,  703,  712,  701,  699,  439,  709,  778,  452,
      449,  715,  449,  697,  706,  695,  693,  446,  703,  778,
      459,  456,  709,  456,  691,  700,  689,  687,  454,  697,
      778,  467,  464,  703,  465,  685,  694,  683,  681,  462,
      691,  778,  475,  476,  697,  468,  679,  688,  677,  675,
      469,  685,  778,  482,  482,  691,  479,  673,  682,  671,
      669,  478,  679,  493,  685,  778,  662,  663,  666,  665,
      486,  669,  663,  667,  663,  671,  498,  497,  778,  499,

      670,  501,  778,  503,  505,  778,  507,  669,  668,  509,
      778,  511,  513,  778,  515,  517,  778,  519,  521,  778,
      523,  529,  528,  778,  529,  530,  778,  534,  662,  646,
      654,  657,  661,  653,  650,  655,  653,  642,  535,  536,
      540,  541,  542,  546,  547,  548,  552,  558,  642,  650,
      638,  640,  651,  546,  562,  639,  563,  566,  635,  646,
      636,  634,  637,  640,  630,  567,  570,  571,  630,  627,
      627,  632,  624,  621,  633,  574,  628,  621,  619,  628,
      621,  623,  620,  619,  613,  614,  613,  615,  621,  575,
      617,  609,  613,  606,  614,  613,  578,  579,  609,  606,

      600,  600,  582,  583,  603,  606,  598,  595,  586,  603,
      587,  600,  594,  590,  591,  596,  597,  594,  598,  593,
      595,  596,  598,  599,  602,  778,  606,  608,  603,  499,
      492,   50,   45,   39,   29,    7,    3
    } ;

static const short int yy_def[338] =
    {   0,
      327,  327,  326,    3,  326,    5,  326,    7,  326,    9,
      326,   11,  326,   13,  326,   15,  326,   17,  326,   19,
      326,   21,  326,   23,  326,   25,  326,   27,  326,  326,
      326,  326,  328,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  328,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  329,  328,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  328,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  330,  328,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  331,  328,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  328,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  328,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  332,
      328,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      333,  328,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  334,  328,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  335,  328,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  336,  328,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  337,  328,  326,  326,  326,  326,
      326,  326,  326,  326,  328,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  329,  326,  329,

      326,  330,  326,  330,  331,  326,  331,  326,  326,  332,
      326,  332,  333,  326,  333,  334,  326,  334,  335,  326,
      335,  326,  336,  326,  336,  337,  326,  337,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  329,  330,
      331,  332,  333,  334,  335,  336,  337,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,    0,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326
    } ;

static const short int yy_nxt[807] =
    {   0,
      326,   31,   32,   31,  226,  184,   33,  184,  223,  187,
       34,   35,  184,  193,  184,   36,  187,  194,   37,   38,
      199,  193,   39,  200,  188,  194,   40,   31,   32,   31,
      219,  188,   33,  197,  187,  197,   34,   35,  193,  193,
      216,   36,  194,  194,   37,   38,  213,  203,   39,  188,
      204,  210,   40,   41,   42,   32,   42,   41,   41,   43,
       44,   41,   41,   45,   46,   41,   41,   41,   47,   41,
       41,   48,   49,   41,   41,   50,   41,   41,   41,   51,
       41,   52,   53,   32,   53,   52,   54,   55,   52,   52,
       52,   56,   57,   52,   52,   52,   58,   52,   52,   59,

       60,   52,   52,   61,   52,   52,   52,   62,   52,   63,
       64,   32,   64,   63,   63,   65,   66,   63,   63,   67,
       68,   63,   63,   63,   69,   63,   63,   70,   71,   63,
       63,   72,   63,   63,   63,   73,   63,   74,   75,   32,
       75,   74,   76,   77,   74,   74,   74,   78,   79,   74,
       74,   74,   80,   74,   74,   81,   82,   74,   74,   83,
       74,   74,   74,   84,   74,   85,   86,   32,   86,   85,
       87,   88,   85,   85,   85,   89,   90,   85,   85,   85,
       91,   85,   85,   92,   93,   85,   85,   94,   85,   85,
       85,   95,   85,   96,   97,   32,   97,   96,   96,   98,

       99,   96,   96,  100,  101,   96,   96,   96,  102,   96,
       96,  103,  104,   96,   96,  105,   96,   96,   96,  106,
       96,  107,  108,   32,  108,  107,  107,  109,  110,  107,
      107,  111,  112,  107,  107,  107,  113,  107,  107,  114,
      115,  107,  107,  116,  107,  107,  107,  117,  107,  118,
      119,   32,  119,  118,  120,  121,  118,  118,  118,  122,
      123,  118,  118,  118,  124,  118,  118,  125,  126,  118,
      118,  127,  118,  118,  118,  128,  118,  129,  130,   32,
      130,  129,  131,  132,  129,  129,  129,  133,  134,  129,
      129,  129,  135,  129,  129,  136,  137,  129,  129,  138,

      129,  129,  129,  139,  129,  140,  141,   32,  141,  140,
      142,  143,  140,  140,  140,  144,  145,  140,  140,  140,
      146,  140,  140,  147,  148,  140,  140,  149,  140,  140,
      140,  150,  140,  151,  152,   32,  152,  151,  153,  154,
      151,  151,  151,  155,  156,  151,  151,  151,  157,  151,
      151,  158,  159,  151,  151,  160,  151,  151,  151,  161,
      151,  162,  163,   32,  163,  162,  164,  165,  162,  162,
      162,  166,  167,  162,  162,  162,  168,  162,  162,  169,
      170,  162,  162,  171,  162,  162,  162,  172,  162,  173,
      174,   32,  174,  173,  175,  176,  173,  173,  173,  177,

      178,  173,  173,  173,  179,  173,  173,  180,  181,  173,
      173,  182,  173,  173,  173,  183,  173,  184,  187,  184,
      184,  187,  184,  193,  184,  206,  184,  194,  207,  187,
      193,  187,  187,  188,  194,  184,  188,  184,  193,  184,
      211,  184,  194,  212,  188,  193,  188,  188,  184,  194,
      184,  187,  193,  184,  214,  184,  194,  215,  187,  193,
      184,  217,  184,  194,  218,  187,  188,  193,  184,  220,
      184,  194,  221,  188,  187,  193,  222,  187,  222,  194,
      188,  224,  193,  184,  225,  184,  194,  227,  187,  188,
      228,  193,  188,  205,  184,  194,  184,  233,  234,  197,

      202,  197,  199,  188,  239,  200,  203,  200,  240,  204,
      206,  204,  241,  207,  211,  207,  242,  212,  214,  212,
      243,  215,  217,  215,  244,  218,  220,  218,  245,  221,
      222,  221,  222,  224,  246,  227,  225,  225,  228,  247,
      199,  203,  228,  200,  204,  206,  211,  214,  207,  212,
      215,  217,  220,  224,  218,  221,  225,  227,  264,  258,
      228,  258,  265,  266,  268,  266,  268,  258,  266,  258,
      266,  276,  268,  276,  268,  276,  297,  276,  297,  297,
      304,  297,  304,  309,  304,  309,  304,  309,  315,  309,
      315,  318,  315,  318,  315,  318,  323,  318,  323,  323,

      325,  323,  325,  325,  198,  325,   30,   30,  185,  185,
      324,  322,  321,  320,  319,  317,  316,  314,  313,  312,
      311,  310,  308,  307,  306,  305,  303,  302,  301,  300,
      299,  298,  296,  295,  294,  293,  292,  291,  290,  289,
      288,  287,  286,  285,  284,  283,  282,  281,  280,  279,
      278,  277,  275,  274,  273,  272,  271,  270,  269,  267,
      263,  262,  261,  260,  259,  257,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  209,  208,  201,  196,  238,
      237,  236,  235,  232,  231,  230,  229,  186,  195,  192,
      191,  190,  189,  186,  195,  192,  191,  190,  189,  186,

      195,  192,  191,  190,  189,  186,  195,  192,  191,  190,
      189,  186,  195,  192,  191,  190,  189,  186,  195,  192,
      191,  190,  189,  186,  195,  192,  191,  190,  189,  209,
      186,  195,  192,  191,  190,  189,  208,  186,  195,  192,
      191,  190,  189,  186,  195,  192,  191,  190,  189,  186,
      195,  192,  191,  190,  189,  201,  186,  195,  192,  191,
      190,  189,  186,  195,  192,  191,  190,  189,  196,  186,
      195,  192,  191,  190,  189,  186,  326,   29,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326
    } ;

static const short int yy_chk[807] =
    {   0,
        0,    1,    1,    1,  337,   31,    1,   31,  336,   34,
        1,    1,   42,   39,   42,    1,   45,   39,    1,    1,
       54,   50,    1,   54,   34,   50,    1,    2,    2,    2,
      335,   45,    2,   53,   56,   53,    2,    2,   61,   72,
      334,    2,   61,   72,    2,    2,  333,   76,    2,   56,
       76,  332,    2,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   13,   13,   13,   13,   13,   13,   13,

       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,

       19,   19,   19,   19,   19,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,

       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   64,   67,   64,
       75,   78,   75,   83,   86,   87,   86,   83,   87,   89,
       94,  100,  111,   67,   94,   97,   78,   97,  105,  108,
      120,  108,  105,  120,   89,  116,  100,  111,  119,  116,
      119,  122,  127,  130,  131,  130,  127,  131,  133,  138,
      141,  142,  141,  138,  142,  144,  122,  149,  152,  153,
      152,  149,  153,  133,  155,  160,  163,  166,  163,  160,
      144,  164,  171,  174,  164,  174,  171,  175,  177,  155,
      175,  182,  166,  331,  184,  182,  184,  191,  191,  197,

      330,  197,  198,  177,  200,  198,  202,  200,  204,  202,
      205,  204,  207,  205,  210,  207,  212,  210,  213,  212,
      215,  213,  216,  215,  218,  216,  219,  218,  221,  219,
      222,  221,  222,  223,  225,  226,  223,  225,  226,  228,
      239,  240,  228,  239,  240,  241,  242,  243,  241,  242,
      243,  244,  245,  246,  244,  245,  246,  247,  254,  248,
      247,  248,  254,  255,  257,  255,  257,  258,  266,  258,
      266,  267,  268,  267,  268,  276,  290,  276,  290,  297,
      298,  297,  298,  303,  304,  303,  304,  309,  311,  309,
      311,  314,  315,  314,  315,  318,  321,  318,  321,  323,

      324,  323,  324,  325,  329,  325,  327,  327,  328,  328,
      322,  320,  319,  317,  316,  313,  312,  310,  308,  307,
      306,  305,  302,  301,  300,  299,  296,  295,  294,  293,
      292,  291,  289,  288,  287,  286,  285,  284,  283,  282,
      281,  280,  279,  278,  277,  275,  274,  273,  272,  271,
      270,  269,  265,  264,  263,  262,  261,  260,  259,  256,
      253,  252,  251,  250,  249,  238,  237,  236,  235,  234,
      233,  232,  231,  230,  229,  209,  208,  201,  196,  195,
      194,  193,  192,  190,  189,  188,  187,  185,  183,  181,
      180,  179,  178,  176,  172,  170,  169,  168,  167,  165,

      161,  159,  158,  157,  156,  154,  150,  148,  147,  146,
      145,  143,  139,  137,  136,  135,  134,  132,  128,  126,
      125,  124,  123,  121,  117,  115,  114,  113,  112,  110,
      109,  106,  104,  103,  102,  101,   99,   98,   95,   93,
       92,   91,   90,   88,   84,   82,   81,   80,   79,   77,
       73,   71,   70,   69,   68,   66,   65,   62,   60,   59,
       58,   57,   55,   51,   49,   48,   47,   46,   44,   43,
       40,   38,   37,   36,   35,   33,   29,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
# line 1 "lex_yy"
# line 3 "lex_yy"
/*
 * Copyright (c) 1992, 1993 Arno Augustin, Frank Hoering, University of
 * Erlangen-Nuremberg, Germany.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. All advertising materials mentioning features or use of this software
 *    must display the following acknowledgement:
 *	This product includes software developed by the University of
 *	Erlangen-Nuremberg, Germany.
 * 4. Neither the name of the University nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHORS ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
 * EVENT SHALL THE AUTHORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
 * OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * This software has not been validated by the ``Bundesamt fuer Zulassungen in
 * der Telekommunikation'' of the ``Deutsche Bundepost Telekom'' and thus
 * must not be used for accessing the BTX-Network of the Telekom in Germany.
 *
 * Diese Software hat keine Zulassung durch das Bundesamt fuer Zulassungen in
 * der Telekommunikation der Deutschen Bundespost Telekom und darf daher nicht
 * am Netz der Deutschen Bundespost Telekom in Deutschland betrieben werden.
 */

        /* space for c program and include*/

static int line_number=1;
static int last_number=0;
static char last_string[256];
int setbaud();

dolex()
{
   line_number=1;
   return yylex();
}

#undef yywrap

int yywrap()
{ 
	return 1;
}
#define YYRETURN(c)  {yy_init = 1; yy_start = 0; return (c);}


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = getc( yyin ); \
		result = c == EOF ? 0 : 1; \
		buf[0] = (char) c; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

# line 86 "lex_yy"



	if ( yy_init )
		{
#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( yy_current_buffer )
			yy_init_buffer( yy_current_buffer, yyin );
		else
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();

		yy_init = 0;
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 327 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 778 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_USER_ACTION
# line 88 "lex_yy"
BEGIN(ebaud);
	YY_BREAK
case 2:
YY_USER_ACTION
# line 89 "lex_yy"
{
                  if( setbaud( atoi(yytext) ) == -1) 
                     YYRETURN(line_number)
                  BEGIN(INITIAL);
               }
	YY_BREAK
case 3:
YY_USER_ACTION
# line 94 "lex_yy"
YYRETURN(line_number)
	YY_BREAK
case 4:
YY_USER_ACTION
# line 97 "lex_yy"
BEGIN(ehangupstring);
	YY_BREAK
case 5:
YY_USER_ACTION
# line 98 "lex_yy"
{
                  sethangupstring(yytext);
                  BEGIN(INITIAL);
               }
	YY_BREAK
case 6:
YY_USER_ACTION
# line 102 "lex_yy"
YYRETURN(line_number)
	YY_BREAK
case 7:
YY_USER_ACTION
# line 104 "lex_yy"
BEGIN(econnectstring);
	YY_BREAK
case 8:
YY_USER_ACTION
# line 105 "lex_yy"
{
                  setconnectstring(yytext);
                  BEGIN(INITIAL);
               }
	YY_BREAK
case 9:
YY_USER_ACTION
# line 109 "lex_yy"
YYRETURN(line_number)
	YY_BREAK
case 10:
YY_USER_ACTION
# line 111 "lex_yy"
BEGIN(enodialtonestring);
	YY_BREAK
case 11:
YY_USER_ACTION
# line 112 "lex_yy"
{
                  setnodialtonestring(yytext);
                  BEGIN(INITIAL);
               }
	YY_BREAK
case 12:
YY_USER_ACTION
# line 116 "lex_yy"
YYRETURN(line_number)
	YY_BREAK
case 13:
YY_USER_ACTION
# line 118 "lex_yy"
BEGIN(enocarrierstring);
	YY_BREAK
case 14:
YY_USER_ACTION
# line 119 "lex_yy"
{
                  setnocarrierstring(yytext);
                  BEGIN(INITIAL);
               }
	YY_BREAK
case 15:
YY_USER_ACTION
# line 123 "lex_yy"
YYRETURN(line_number)
	YY_BREAK
case 16:
YY_USER_ACTION
# line 126 "lex_yy"
BEGIN(ebusystring);
	YY_BREAK
case 17:
YY_USER_ACTION
# line 127 "lex_yy"
{
                  setbusystring(yytext);
                  BEGIN(INITIAL);
               }
	YY_BREAK
case 18:
YY_USER_ACTION
# line 131 "lex_yy"
YYRETURN(line_number)
	YY_BREAK
case 19:
YY_USER_ACTION
# line 135 "lex_yy"
BEGIN(edevicespeed);
	YY_BREAK
case 20:
YY_USER_ACTION
# line 136 "lex_yy"
{
                  last_number = atoi(yytext);
                  BEGIN(edevicename);
               }
	YY_BREAK
case 21:
YY_USER_ACTION
# line 140 "lex_yy"
YYRETURN(line_number)
	YY_BREAK
case 22:
YY_USER_ACTION
# line 142 "lex_yy"
{
                  if(-1 == opendevice(yytext,last_number))
		     YYRETURN(line_number)
                  BEGIN(INITIAL);
               }                  
	YY_BREAK
case 23:
YY_USER_ACTION
# line 147 "lex_yy"
/* skip white spaces */
	YY_BREAK
case 24:
YY_USER_ACTION
# line 148 "lex_yy"
YYRETURN(line_number)
	YY_BREAK
case 25:
YY_USER_ACTION
# line 154 "lex_yy"
BEGIN(eisdnport);
	YY_BREAK
case 26:
YY_USER_ACTION
# line 155 "lex_yy"
{
                	  	strcpy(last_string,yytext);
                  		BEGIN(eisdndevice);
            	    }
	YY_BREAK
case 27:
YY_USER_ACTION
# line 159 "lex_yy"
YYRETURN(line_number)
	YY_BREAK
case 28:
YY_USER_ACTION
# line 161 "lex_yy"
{
                  if(-1 == isdn(yytext,last_string))
		     YYRETURN(line_number)
                  BEGIN(INITIAL);
               }                  
	YY_BREAK
case 29:
YY_USER_ACTION
# line 166 "lex_yy"
/* skip white spaces */
	YY_BREAK
case 30:
YY_USER_ACTION
# line 167 "lex_yy"
YYRETURN(line_number)
	YY_BREAK
case 31:
YY_USER_ACTION
# line 172 "lex_yy"
BEGIN(esleep);
	YY_BREAK
case 32:
YY_USER_ACTION
# line 173 "lex_yy"
{
                  wsleep(atoi(yytext));
                  BEGIN(INITIAL);
               }
	YY_BREAK
case 33:
YY_USER_ACTION
# line 177 "lex_yy"
YYRETURN(line_number)
	YY_BREAK
case 34:
YY_USER_ACTION
# line 181 "lex_yy"
BEGIN(esendstring);
	YY_BREAK
case 35:
YY_USER_ACTION
# line 182 "lex_yy"
{
                  sendstring(yytext);
                  BEGIN(INITIAL);
               }
	YY_BREAK
case 36:
YY_USER_ACTION
# line 186 "lex_yy"
YYRETURN(line_number)
	YY_BREAK
case 37:
YY_USER_ACTION
# line 189 "lex_yy"
BEGIN(ewaitnumber);
	YY_BREAK
case 38:
YY_USER_ACTION
# line 190 "lex_yy"
{
                  if(-1 == waitconnect(atoi(yytext))) YYRETURN(line_number);
                  BEGIN(INITIAL);
               }
	YY_BREAK
case 39:
YY_USER_ACTION
# line 194 "lex_yy"
YYRETURN(line_number)
	YY_BREAK
case 40:
YY_USER_ACTION
# line 197 "lex_yy"
/* skip white spaces   */
	YY_BREAK
case 41:
YY_USER_ACTION
# line 199 "lex_yy"
line_number++; /* # skip comment  */
	YY_BREAK
case 42:
YY_USER_ACTION
# line 200 "lex_yy"
line_number++;
	YY_BREAK
case 43:
YY_USER_ACTION
# line 201 "lex_yy"
YYRETURN(line_number) /* ERROR */
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ebaud):
case YY_STATE_EOF(edevicename):
case YY_STATE_EOF(edevicespeed):
case YY_STATE_EOF(ehangupstring):
case YY_STATE_EOF(esendstring):
case YY_STATE_EOF(esleep):
case YY_STATE_EOF(ewaitnumber):
case YY_STATE_EOF(econnectstring):
case YY_STATE_EOF(ebusystring):
case YY_STATE_EOF(enocarrierstring):
case YY_STATE_EOF(enodialtonestring):
case YY_STATE_EOF(eisdndevice):
case YY_STATE_EOF(eisdnport):
# line 202 "lex_yy"
{
                     YYRETURN(0)
                 }
	YY_BREAK
case 44:
YY_USER_ACTION
# line 205 "lex_yy"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = yy_cp - yytext_ptr - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_input_file != yyin )
			{
			/* This can happen if we scan a file, yywrap() returns
			 * 1, and then later the user points yyin at a new
			 * file to resume scanning.  We have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input file.
			 */
			yy_current_buffer->yy_input_file = yyin;
			yy_n_chars = yy_current_buffer->yy_n_chars;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr - 1; /* copy prev. char, too */
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = yy_c_buf_p - yytext_ptr;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_eof_status != EOF_NOT_SEEN )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset = yy_c_buf_p - b->yy_ch_buf;

			b->yy_buf_size *= 2;
			b->yy_ch_buf = (char *)
				yy_flex_realloc( (void *) b->yy_ch_buf,
						 b->yy_buf_size );

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move - YY_MORE_ADJ == 1 )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_eof_status = EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	/* yytext begins at the second character in yy_ch_buf; the first
	 * character is the one which preceded it before reading in the latest
	 * buffer; it needs to be kept around in case it's a newline, so
	 * yy_get_previous_state() will have with '^' rules active.
	 */

	yytext_ptr = &yy_current_buffer->yy_ch_buf[1];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 327 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 327 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 326);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += dest - source;
		yy_bp += dest - source;
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
		yy_cp[-2] = '\n';

	*--yy_cp = (char) c;


	/* Note: the formal parameter *must* be called "yy_bp" for this
	 * macro to now work correctly.
	 */
	YY_DO_BEFORE_ACTION; /* set up yytext again */
	}


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *yy_c_buf_p;
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );

	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );

	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	yy_flex_free( (void *) b->yy_ch_buf );
	yy_flex_free( (void *) b );
	}


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif
	{
	b->yy_input_file = file;

	/* We put in the '\n' and start reading from [1] so that an
	 * initial match-at-newline will be true.
	 */

	b->yy_ch_buf[0] = '\n';
	b->yy_n_chars = 1;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[1];

	b->yy_is_interactive = file ? isatty( fileno(file) ) : 0;

	b->yy_fill_buffer = 1;

	b->yy_eof_status = EOF_NOT_SEEN;
	}


#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		int new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}


static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}


static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}


#ifdef YY_USE_PROTOS
static void yy_fatal_error( const char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( 1 );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strcpy( char *s1, const char *s2 )
#else
static void yy_flex_strcpy( s1, s2 )
char *s1;
const char *s2;
#endif
	{
	while ( (*(s1++) = *(s2++)) )
		;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( unsigned int size )
#else
static void *yy_flex_alloc( size )
unsigned int size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, unsigned int size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
unsigned int size;
#endif
	{
	return (void *) realloc( ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}
# line 205 "lex_yy"





